language: objective-c
osx_image: xcode6.4
script: ./build.sh
env:
        - BUILDTOOL=xcodebuild
        - BUILDTOOL=xctool
env:
  global:
    DEPLOY_HOST=55a1cc835004460171000096@builds.koszek.com
    DEPLOY_LOCATION=app-root/runtime/repo/
    DEPLOY_KEY=9acbb13b487b
    DEPLOY_FILE=travis_deploy/cs193p

after_success:
- make pack
- RELFILENAME=`make relfilename`
- git clone https://github.com/wkoszek/travis_deploy.git
- ./travis_deploy/deploy.sh ${RELFILENAME}
